name: Deploy Next.js App

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fix permissions
        run: sudo chown -R runner:runner .

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.4
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Deploy to /var/www/app/portfolio-next
        run: |
          sudo rm -rf /var/www/app/portfolio-next
          sudo mkdir -p /var/www/app/portfolio-next
          sudo cp -r . /var/www/app/portfolio-next
          sudo chown -R root:root /var/www/app/portfolio-next

      - name: Restart app with PM2
        run: |
          sudo pm2 restart nextjs || sudo pm2 start npm --name "nextjs" -- start --prefix /var/www/app/portfolio-next
          sudo pm2 save

      - name: Clean up temp files
        run: rm -rf /home/runner/actions-runner/_work/*
