name: Deploy to Nginx

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to Nginx
        run: |
          # Убедимся что папки существуют
          mkdir -p /var/www/html/_next
          
          # Копируем с сохранением прав
          cp -R .next/static /var/www/html/_next/
          cp -R public/* /var/www/html/
          
          # Перезапускаем Nginx через sudo (если настроили NOPASSWD)
          sudo -n systemctl restart nginx

      - name: Verify deployment
        run: |
          ls -la /var/www/html
          curl -I http://localhost